import type { Product, ShippingZone, Order } from "@/types";
import { supabase } from "./supabase";

export async function getProducts() {
  const { data, error } = await supabase
    .from('products')
    .select('*')
    .order('created_at', { ascending: false });

  if (error || !data || data.length === 0) {
    console.log('Using demo products (Supabase error or empty table)');
    return demoProducts;
  }
  return data;
}

export async function getOrders() {
  const { data, error } = await supabase
    .from('orders')
    .select('*')
    .order('created_at', { ascending: false });

  if (error || !data) {
    return [];
  }
  return data;
}

export const demoProducts: Product[] = [
  {
    id: 1,
    name_ar: "COSRX Advanced Snail 96 Mucin Power Essence",
    name_en: "COSRX Advanced Snail 96 Mucin Power Essence",
    price_egp: 650,
    compare_price_egp: 800,
    description_ar: "إسينس بقوة ميوسين الحلزون 96% لترطيب عميق وإصلاح البشرة التالفة. تركيبة خفيفة تمتصها البشرة بسرعة وتمنحها نعومة وإشراقة فورية.",
    description_en: "96% Snail Mucin Power Essence for deep hydration and skin repair. Lightweight formula that absorbs quickly, leaving skin soft and radiant instantly.",
    ingredients_ar: "ميوسين الحلزون 96%، بيتين، حمض الهيالورونيك، بانثينول، أرجينين، ألانتوين",
    ingredients_en: "Snail Secretion Filtrate (96%), Betaine, Hyaluronic Acid, Panthenol, Arginine, Allantoin",
    category: "Skincare",
    brand: "COSRX",
    stock: 25,
    low_stock_threshold: 10,
    sku: "COSRX-SNL-96",
    weight_kg: 0.15,
    images: ["/products/cosrx-snail.webp"],
    main_image: "/products/cosrx-snail.webp",
    slug: "cosrx-advanced-snail-96-mucin-power-essence",
    meta_title_ar: "COSRX إسينس الحلزون | كوزمو ستيشن",
    meta_title_en: "COSRX Snail Mucin Essence | Cozmo Station",
    meta_description_ar: "اشتري COSRX Advanced Snail 96 Mucin Power Essence الأصلي في مصر. ترطيب عميق وإصلاح البشرة.",
    meta_description_en: "Buy authentic COSRX Advanced Snail 96 Mucin Power Essence in Egypt. Deep hydration and skin repair.",
    is_active: true,
    is_new: false,
    is_featured: true,
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: 2,
    name_ar: "Beauty of Joseon Relief Sun Rice + Probiotics SPF50",
    name_en: "Beauty of Joseon Relief Sun Rice + Probiotics SPF50",
    price_egp: 450,
    compare_price_egp: null,
    description_ar: "واقي شمس بتركيبة الأرز والبروبيوتيك SPF50+ PA++++ يحمي من أشعة الشمس بدون أثر أبيض. خفيف كالماء ومناسب لجميع أنواع البشرة.",
    description_en: "Rice + Probiotics sunscreen SPF50+ PA++++ that protects without white cast. Lightweight, water-like texture suitable for all skin types.",
    ingredients_ar: "مستخلص نخالة الأرز، البروبيوتيك، النياسيناميد، حمض الهيالورونيك",
    ingredients_en: "Rice Bran Extract, Probiotics, Niacinamide, Hyaluronic Acid",
    category: "Skincare",
    brand: "Beauty of Joseon",
    stock: 40,
    low_stock_threshold: 10,
    sku: "BOJ-SUN-SPF50",
    weight_kg: 0.08,
    images: ["/products/boj-sun.webp"],
    main_image: "/products/boj-sun.webp",
    slug: "beauty-of-joseon-relief-sun-rice-probiotics-spf50",
    meta_title_ar: "واقي شمس Beauty of Joseon | كوزمو ستيشن",
    meta_title_en: "Beauty of Joseon Sunscreen | Cozmo Station",
    meta_description_ar: "واقي شمس Beauty of Joseon بالأرز والبروبيوتيك SPF50 - خفيف بدون أثر أبيض",
    meta_description_en: "Beauty of Joseon Relief Sun with Rice & Probiotics SPF50 - lightweight, no white cast",
    is_active: true,
    is_new: true,
    is_featured: true,
    created_at: "2024-02-01T10:00:00Z",
  },
  {
    id: 3,
    name_ar: "Anua Heartleaf 77% Soothing Toner",
    name_en: "Anua Heartleaf 77% Soothing Toner",
    price_egp: 550,
    compare_price_egp: 680,
    description_ar: "تونر مهدئ بخلاصة نبات الهارتليف 77% يهدئ البشرة الحساسة والمتهيجة. ينظم إفراز الدهون ويقلل الاحمرار ويرطب البشرة بعمق.",
    description_en: "77% Heartleaf soothing toner that calms sensitive and irritated skin. Regulates sebum, reduces redness, and deeply moisturizes.",
    ingredients_ar: "مستخلص أوراق الهارتليف 77%، بانثينول، حمض الهيالورونيك، ماء الأرز",
    ingredients_en: "Houttuynia Cordata Extract (77%), Panthenol, Hyaluronic Acid, Rice Water",
    category: "Skincare",
    brand: "Anua",
    stock: 18,
    low_stock_threshold: 10,
    sku: "ANUA-HL77-TN",
    weight_kg: 0.25,
    images: ["/products/anua-toner.webp"],
    main_image: "/products/anua-toner.webp",
    slug: "anua-heartleaf-77-soothing-toner",
    meta_title_ar: "Anua تونر الهارتليف المهدئ | كوزمو ستيشن",
    meta_title_en: "Anua Heartleaf Soothing Toner | Cozmo Station",
    meta_description_ar: "تونر Anua Heartleaf 77% المهدئ للبشرة الحساسة - أصلي من كوريا",
    meta_description_en: "Anua Heartleaf 77% Soothing Toner for sensitive skin - authentic from Korea",
    is_active: true,
    is_new: false,
    is_featured: true,
    created_at: "2024-01-20T10:00:00Z",
  },
  {
    id: 4,
    name_ar: "Numbuzin No.3 Skin Softening Serum",
    name_en: "Numbuzin No.3 Skin Softening Serum",
    price_egp: 720,
    compare_price_egp: 850,
    description_ar: "سيروم تنعيم البشرة رقم 3 من نمبوزين. يحتوي على حمض الجلوتاثيون والجلاثيون لتفتيح البشرة وتوحيد لونها مع ترطيب عميق.",
    description_en: "Skin softening serum No.3 by Numbuzin. Contains Glutathione for brightening and evening skin tone with deep hydration.",
    ingredients_ar: "الجلوتاثيون، النياسيناميد، حمض الهيالورونيك، السيراميد، البانثينول",
    ingredients_en: "Glutathione, Niacinamide, Hyaluronic Acid, Ceramide, Panthenol",
    category: "Skincare",
    brand: "Numbuzin",
    stock: 12,
    low_stock_threshold: 10,
    sku: "NMBZ-NO3-SRM",
    weight_kg: 0.08,
    images: ["/products/numbuzin-serum.webp"],
    main_image: "/products/numbuzin-serum.webp",
    slug: "numbuzin-no3-skin-softening-serum",
    meta_title_ar: "Numbuzin سيروم تنعيم البشرة | كوزمو ستيشن",
    meta_title_en: "Numbuzin Skin Softening Serum | Cozmo Station",
    meta_description_ar: "سيروم Numbuzin No.3 لتنعيم وتفتيح البشرة - أصلي من كوريا في مصر",
    meta_description_en: "Numbuzin No.3 Skin Softening Serum - authentic Korean skincare in Egypt",
    is_active: true,
    is_new: true,
    is_featured: false,
    created_at: "2024-02-10T10:00:00Z",
  },
  {
    id: 5,
    name_ar: "Illiyoon Ceramide Ato Concentrate Cream",
    name_en: "Illiyoon Ceramide Ato Concentrate Cream",
    price_egp: 580,
    compare_price_egp: null,
    description_ar: "كريم مركز بالسيراميد لترطيب فائق وحماية حاجز البشرة. مناسب للبشرة الجافة والحساسة ولجميع أفراد العائلة.",
    description_en: "Ceramide concentrate cream for superior moisturization and skin barrier protection. Suitable for dry, sensitive skin and the whole family.",
    ingredients_ar: "سيراميد، بانثينول، شيا بتر، سكوالين، حمض الهيالورونيك",
    ingredients_en: "Ceramide, Panthenol, Shea Butter, Squalane, Hyaluronic Acid",
    category: "Skincare",
    brand: "Illiyoon",
    stock: 30,
    low_stock_threshold: 10,
    sku: "ILLY-CRM-ATO",
    weight_kg: 0.20,
    images: ["/products/illiyoon-cream.webp"],
    main_image: "/products/illiyoon-cream.webp",
    slug: "illiyoon-ceramide-ato-concentrate-cream",
    meta_title_ar: "Illiyoon كريم السيراميد | كوزمو ستيشن",
    meta_title_en: "Illiyoon Ceramide Cream | Cozmo Station",
    meta_description_ar: "كريم Illiyoon بالسيراميد لترطيب وحماية البشرة - مناسب للبشرة الحساسة",
    meta_description_en: "Illiyoon Ceramide Ato Concentrate Cream for deep moisturization and skin barrier protection",
    is_active: true,
    is_new: false,
    is_featured: true,
    created_at: "2024-01-25T10:00:00Z",
  },
  {
    id: 6,
    name_ar: "Mise-en-scène Perfect Serum Hair Oil",
    name_en: "Mise-en-scène Perfect Serum Hair Oil",
    price_egp: 380,
    compare_price_egp: 450,
    description_ar: "زيت سيروم الشعر المثالي من ميزانسين. يغذي الشعر التالف ويمنحه لمعاناً وحيوية. تركيبة خفيفة لا تثقل الشعر.",
    description_en: "Perfect hair serum oil by Mise-en-scène. Nourishes damaged hair for shine and vitality. Lightweight formula that won't weigh hair down.",
    ingredients_ar: "زيت الأرجان، زيت الكاميليا، زيت الجوجوبا، زيت عباد الشمس، فيتامين E",
    ingredients_en: "Argan Oil, Camellia Oil, Jojoba Oil, Sunflower Oil, Vitamin E",
    category: "Haircare",
    brand: "Mise-en-scène",
    stock: 35,
    low_stock_threshold: 10,
    sku: "MES-PRF-OIL",
    weight_kg: 0.10,
    images: ["/products/mise-hair-oil.webp"],
    main_image: "/products/mise-hair-oil.webp",
    slug: "mise-en-scene-perfect-serum-hair-oil",
    meta_title_ar: "زيت الشعر Mise-en-scène | كوزمو ستيشن",
    meta_title_en: "Mise-en-scène Hair Oil | Cozmo Station",
    meta_description_ar: "زيت سيروم الشعر المثالي من Mise-en-scène لتغذية ولمعان الشعر",
    meta_description_en: "Mise-en-scène Perfect Serum Hair Oil for nourished, shiny hair",
    is_active: true,
    is_new: false,
    is_featured: false,
    created_at: "2024-01-18T10:00:00Z",
  },
  {
    id: 7,
    name_ar: "ROUND LAB Birch Juice Moisturizing Sunscreen",
    name_en: "ROUND LAB Birch Juice Moisturizing Sunscreen",
    price_egp: 490,
    compare_price_egp: null,
    description_ar: "واقي شمس مرطب بعصارة البتولا. يحمي من أشعة UVA/UVB ويرطب البشرة في نفس الوقت. مثالي للاستخدام اليومي.",
    description_en: "Moisturizing sunscreen with birch juice. Protects from UVA/UVB rays while hydrating skin. Perfect for daily use.",
    ingredients_ar: "عصارة البتولا، حمض الهيالورونيك، النياسيناميد، فيلتر شمسي واسع الطيف",
    ingredients_en: "Birch Juice, Hyaluronic Acid, Niacinamide, Broad Spectrum UV Filters",
    category: "Skincare",
    brand: "ROUND LAB",
    stock: 22,
    low_stock_threshold: 10,
    sku: "RLAB-BJ-SUN",
    weight_kg: 0.08,
    images: ["/products/roundlab-sun.webp"],
    main_image: "/products/roundlab-sun.webp",
    slug: "round-lab-birch-juice-moisturizing-sunscreen",
    meta_title_ar: "واقي شمس ROUND LAB | كوزمو ستيشن",
    meta_title_en: "ROUND LAB Sunscreen | Cozmo Station",
    meta_description_ar: "واقي شمس ROUND LAB بعصارة البتولا مرطب وحامي - أصلي من كوريا",
    meta_description_en: "ROUND LAB Birch Juice Moisturizing Sunscreen - authentic Korean suncare",
    is_active: true,
    is_new: true,
    is_featured: false,
    created_at: "2024-02-05T10:00:00Z",
  },
  {
    id: 8,
    name_ar: "Dr.G R.E.D Blemish Clear Soothing Cream",
    name_en: "Dr.G R.E.D Blemish Clear Soothing Cream",
    price_egp: 620,
    compare_price_egp: 750,
    description_ar: "كريم مهدئ ومعالج للبقع والشوائب من دكتور جي. يهدئ البشرة المتهيجة ويقلل الاحمرار ويساعد في تقليل آثار حب الشباب.",
    description_en: "Blemish clearing and soothing cream by Dr.G. Calms irritated skin, reduces redness, and helps diminish acne marks.",
    ingredients_ar: "الزنك، السنتيلا أسياتيكا، شجرة الشاي، حمض الأزيلايك، البانثينول",
    ingredients_en: "Zinc, Centella Asiatica, Tea Tree, Azelaic Acid, Panthenol",
    category: "Skincare",
    brand: "Dr.G",
    stock: 8,
    low_stock_threshold: 10,
    sku: "DRG-RED-CLR",
    weight_kg: 0.10,
    images: ["/products/drg-blemish.webp"],
    main_image: "/products/drg-blemish.webp",
    slug: "dr-g-red-blemish-clear-soothing-cream",
    meta_title_ar: "Dr.G كريم معالج البقع | كوزمو ستيشن",
    meta_title_en: "Dr.G Blemish Cream | Cozmo Station",
    meta_description_ar: "كريم Dr.G R.E.D لعلاج البقع وتهدئة البشرة - أصلي من كوريا في مصر",
    meta_description_en: "Dr.G R.E.D Blemish Clear Soothing Cream for clear, calm skin",
    is_active: true,
    is_new: false,
    is_featured: true,
    created_at: "2024-01-22T10:00:00Z",
  },
];

export const shippingZones: ShippingZone[] = [
  {
    id: "cairo",
    name_ar: "القاهرة الكبرى",
    name_en: "Greater Cairo",
    governorates_ar: ["القاهرة", "الجيزة", "القليوبية"],
    governorates_en: ["Cairo", "Giza", "Qalyubia"],
    cost_egp: 35,
    delivery_days: "2-3",
  },
  {
    id: "alex",
    name_ar: "الإسكندرية",
    name_en: "Alexandria",
    governorates_ar: ["الإسكندرية", "مطروح"],
    governorates_en: ["Alexandria", "Matrouh"],
    cost_egp: 40,
    delivery_days: "3-4",
  },
  {
    id: "delta",
    name_ar: "الوجه البحري",
    name_en: "Delta (Lower Egypt)",
    governorates_ar: ["الدقهلية", "الشرقية", "الغربية", "المنوفية", "كفر الشيخ", "دمياط", "بورسعيد"],
    governorates_en: ["Dakahlia", "Sharqia", "Gharbia", "Menoufia", "Kafr El Sheikh", "Damietta", "Port Said"],
    cost_egp: 45,
    delivery_days: "3-5",
  },
  {
    id: "canal",
    name_ar: "القناة وسيناء",
    name_en: "Canal & Sinai",
    governorates_ar: ["الإسماعيلية", "السويس", "شمال سيناء", "جنوب سيناء"],
    governorates_en: ["Ismailia", "Suez", "North Sinai", "South Sinai"],
    cost_egp: 55,
    delivery_days: "4-6",
  },
  {
    id: "north-upper",
    name_ar: "شمال الصعيد",
    name_en: "North Upper Egypt",
    governorates_ar: ["بني سويف", "المنيا", "الفيوم"],
    governorates_en: ["Beni Suef", "Minya", "Fayoum"],
    cost_egp: 60,
    delivery_days: "5-7",
  },
  {
    id: "south-upper",
    name_ar: "جنوب الصعيد",
    name_en: "South Upper Egypt",
    governorates_ar: ["أسيوط", "سوهاج", "قنا", "الأقصر", "أسوان"],
    governorates_en: ["Asyut", "Sohag", "Qena", "Luxor", "Aswan"],
    cost_egp: 75,
    delivery_days: "7-10",
  },
  {
    id: "remote",
    name_ar: "الوادي الجديد والبحر الأحمر",
    name_en: "New Valley & Red Sea",
    governorates_ar: ["الوادي الجديد", "البحر الأحمر"],
    governorates_en: ["New Valley", "Red Sea"],
    cost_egp: 90,
    delivery_days: "7-10",
  },
];
